language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
jobs:
  include:
    - stage: release
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
stages:
  - test
  - name: release
    if: branch = master
