language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
after_success:
  - npm run build
jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
